name: .NET Tests

on: [push, pull_request]

jobs:
  test:

    name: Test on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          arch: x86
          target: win
        - os: windows-latest
          arch: x64
          target: win
        - os: ubuntu-latest
          arch: x64
          target: linux
        - os: macos-latest
          arch: x64
          target: osx
    timeout-minutes: 30

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2.4.0
      
    - name: Setup .Net
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'

    - if: ${{ matrix.target }} == ubuntu-latest
      name: Install libsodium
      run: |
        apt-get update -y
        apt-get install libsodium
      
    - name: Restore
      run: dotnet restore --runtime ${{ matrix.target }}-${{ matrix.arch }}
      
    - name: Test
      run: dotnet test --arch ${{ matrix.arch }}
