name: .NET QEMU Tests
on: [push, pull_request]

jobs:
  test_qemu:
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu20.04
          - arch: aarch64
            distro: ubuntu20.04
          - arch: aarch64
            distro: alpine_latest

    steps:
      - uses: actions/checkout@v2.1.0
      
      - uses: uraimo/run-on-arch-action@v2
        name: Test
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}

          env: |
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true

          shell: /bin/bash
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*)
                apt-get update -y
                apt-get install -y wget ca-certificates openssl
                printf "\nca_directory=/etc/ssl/certs" | sudo tee -a /etc/wgetrc
                wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
                dpkg -i packages-microsoft-prod.deb
                rm packages-microsoft-prod.deb
                apt-get update -y
                apt-get install -y dotnet-sdk-6.0
                ;;
              alpine*)
                apk update
                apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
                apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
                wget https://dot.net/v1/dotnet-install.sh
                chmod 777 dotnet-install.sh
                ./dotnet-install.sh -c 6.0
                rm dotnet-install.sh
                ;;
            esac

          run: |
            dotnet test --logger "console;verbosity=detailed"
